Unit test
comp523-swayambhu-org/comp523-swayambhu pull request #11
Opened 2023-12-03 20:00 UTC by jessikka12

css code cleanup and added a unit test for the annotation test

2023-12-04 04:13 UTC, charlesma11 requested changes

2023-12-04 04:13 UTC, charlesma11 commented on src/tests/annotation.test.js
> +//assert the expected result
can we get some more assertions here?

2023-12-04 14:41 UTC, jessikka12 commented on src/tests/annotation.test.js
> +//assert the expected result
what kind of assertions were you thinking?

2023-12-04 21:02 UTC, charlesma11 requested changes

2023-12-04 21:02 UTC, charlesma11 commented on src/tests/annotation.test.js
> +//assert the expected result
make sure this works for edge cases (i.e. should go back to origin when a different number is inputted that is not in range)
also add for tests other than annotation

2023-12-04 21:41 UTC, jessikka12 commented on src/tests/annotation.test.js
> +//assert the expected result
ok, so we want a more expansive test suite. sure I can write more unit tests. 

but what do you mean by out of range and going back to origin? we don't have a range or an origin in the react code.

2023-12-04 21:59 UTC, charlesma11 commented on src/tests/annotation.test.js
> +//assert the expected result
if a user clicks on a the "view location" button, it takes them to an annotation with the "id" of the annotation number. Say the "id" sent is somehow a different number (like 100), then it should just return the origin position (which is 0). Basically testing the `handleShowLocation` method

2023-12-04 22:28 UTC, jessikka12 commented on src/tests/annotation.test.js
> +//assert the expected result
isn't the code for that on the unity side? the `handleShowLocation` method just directly passes the number into the `showMessage` method which is passed in from unity in App.js. We don't do any checks on the number because our annotations are out of order right now (they go 1, 11, 12, 20). 

```
  const handleShowLocation = (num) => {
    console.log(num);
    sendMessage('0_annotation_camera', 'SetLocation', num);
  };
```

also, checking that the "view location" button sends the player to the right location in the model is an integration test.

2023-12-04 22:31 UTC, charlesma11 commented on src/tests/annotation.test.js
> +//assert the expected result
Ok in that case no need to do the out of range test. We should add functionality on the front end to make sure the function doesn't pass in wrong numbers in the first place.

2023-12-08 16:48 UTC, charlesma11 approved these changes

2023-12-08 16:49 UTC, merged